/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConfigC;
import Controlador.PagosC;
import com.sun.rowset.CachedRowSetImpl;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class JDPagos extends javax.swing.JDialog {

    DefaultTableModel dtm;
    Object v[] = {"IDpago", "IDpedido", "Fecha", "Valor", "LugarPago"};

    DefaultTableModel dtm2;
    Object v2[] = {"IDPRODUCTO", "NOMBRE", "VALOR", "CANTIDAD", "SUBTOTAL"};

    /**
     * Creates new form JDPagos
     */
    public JDPagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm = new DefaultTableModel(null, v);

        dtm2 = new DefaultTableModel(null, v2);
        jtablaProd.setModel(dtm2);
        jtPagos.setModel(dtm);
        for (Component Component : jPanelinfCliente.getComponents()) {
            Component.setEnabled(false);
        }
        for (Component Component : jPanelinfEmpleado.getComponents()) {
            Component.setEnabled(false);
        }
        for (Component Component : jPanelinfPedido1.getComponents()) {
            Component.setEnabled(false);
        }
        for (Component Component : jPanel1.getComponents()) {
            Component.setEnabled(false);
        }
        for (Component Component : jPanel2.getComponents()) {
            Component.setEnabled(false);
        }
        txtCodPedido1.setEnabled(true);
        poblarSedes();
        traerCodP();
        obtenerFecha();
        jdcfechapago.setEnabled(false);
        CargarCargo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelinfCliente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtidCliente = new javax.swing.JTextField();
        txtNomCliente = new javax.swing.JTextField();
        txtTelCliente = new javax.swing.JTextField();
        txtDirCliente = new javax.swing.JTextField();
        jPanelinfEmpleado = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtidEmpleado = new javax.swing.JTextField();
        txtNomEmp = new javax.swing.JTextField();
        cbxGeneroEmp = new javax.swing.JComboBox<>();
        cbxCargo = new javax.swing.JComboBox<>();
        txtApeEmp = new javax.swing.JTextField();
        jPanelinfPedido1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCodPedido1 = new javax.swing.JTextField();
        txtFechaPedido1 = new javax.swing.JTextField();
        jdcFentrega1 = new com.toedter.calendar.JDateChooser();
        cbxFormaPago1 = new javax.swing.JComboBox<>();
        cbEstadoPed = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorDeuda = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        txtValorPagado = new javax.swing.JTextField();
        txtCantPagos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaProd = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        rbIdPago = new javax.swing.JRadioButton();
        rbIdPedido = new javax.swing.JRadioButton();
        rbFecha = new javax.swing.JRadioButton();
        txtBuscarPagos = new javax.swing.JTextField();
        jdcBuscarxFecha = new com.toedter.calendar.JDateChooser();
        btnBuscarPago = new javax.swing.JButton();
        btnLimpiarBPagos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPagos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtidpago = new javax.swing.JTextField();
        txtidpedido = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        btnbxidpago = new javax.swing.JButton();
        btnbxidpedido = new javax.swing.JButton();
        btnbxidcliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbxlugarpago = new javax.swing.JComboBox<>();
        jdcfechapago = new com.toedter.calendar.JDateChooser();
        txtcompobante = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelinfCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Inf Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel11.setText("Identificacion");

        jLabel12.setText("Nombre Cliente");

        jLabel13.setText("Telefono");

        jLabel14.setText("Direccion");

        txtNomCliente.setEnabled(false);

        txtTelCliente.setEnabled(false);

        txtDirCliente.setEnabled(false);

        javax.swing.GroupLayout jPanelinfClienteLayout = new javax.swing.GroupLayout(jPanelinfCliente);
        jPanelinfCliente.setLayout(jPanelinfClienteLayout);
        jPanelinfClienteLayout.setHorizontalGroup(
            jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txtNomCliente)
                    .addComponent(txtTelCliente)
                    .addComponent(txtDirCliente))
                .addGap(103, 103, 103))
        );
        jPanelinfClienteLayout.setVerticalGroup(
            jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfClienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelinfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanelinfEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Inf Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel15.setText("Identificacion");

        jLabel16.setText("Nombre");

        jLabel17.setText("Apellidos");

        jLabel18.setText("Genero");

        jLabel19.setText("Cargo");

        txtidEmpleado.setEnabled(false);

        txtNomEmp.setEnabled(false);

        cbxGeneroEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino" }));

        cbxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        javax.swing.GroupLayout jPanelinfEmpleadoLayout = new javax.swing.GroupLayout(jPanelinfEmpleado);
        jPanelinfEmpleado.setLayout(jPanelinfEmpleadoLayout);
        jPanelinfEmpleadoLayout.setHorizontalGroup(
            jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfEmpleadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxCargo, 0, 148, Short.MAX_VALUE)
                        .addComponent(cbxGeneroEmp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtApeEmp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNomEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelinfEmpleadoLayout.setVerticalGroup(
            jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtApeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbxGeneroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelinfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanelinfPedido1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Inf Pedido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel20.setText("Codigo Pedido");

        jLabel21.setText("Fecha Pedido");

        jLabel22.setText("Fecha Entrega");

        jLabel23.setText("Forma Pago");

        txtCodPedido1.setEnabled(false);
        txtCodPedido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodPedido1KeyTyped(evt);
            }
        });

        txtFechaPedido1.setEnabled(false);

        cbxFormaPago1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Contado", "Credito" }));

        cbEstadoPed.setText("Estado");

        javax.swing.GroupLayout jPanelinfPedido1Layout = new javax.swing.GroupLayout(jPanelinfPedido1);
        jPanelinfPedido1.setLayout(jPanelinfPedido1Layout);
        jPanelinfPedido1Layout.setHorizontalGroup(
            jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfPedido1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFormaPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcFentrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoPed))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelinfPedido1Layout.setVerticalGroup(
            jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfPedido1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCodPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtFechaPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jdcFentrega1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelinfPedido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbxFormaPago1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(cbEstadoPed)
                .addGap(18, 18, 18))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Cant Pagos");

        jLabel2.setText("Valor Pagado");

        jLabel3.setText("Valor Deuda");

        jLabel4.setText("Valor Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorTotal)
                    .addComponent(txtValorDeuda)
                    .addComponent(txtValorPagado)
                    .addComponent(txtCantPagos))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inf Productos"));

        jtablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPRODUCTO", "NOMBRE", "VALOR", "CANTIDAD", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(jtablaProd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(rbIdPago);
        rbIdPago.setText("IdPago");

        buttonGroup1.add(rbIdPedido);
        rbIdPedido.setText("IdPedido");

        buttonGroup1.add(rbFecha);
        rbFecha.setText("Fecha");

        btnBuscarPago.setText("Buscar");
        btnBuscarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPagoActionPerformed(evt);
            }
        });

        btnLimpiarBPagos.setText("Limpiar");
        btnLimpiarBPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBPagosActionPerformed(evt);
            }
        });

        jtPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPago", "IdPedido", "Fecha", "Valor", "Lugar de Pago"
            }
        ));
        jScrollPane2.setViewportView(jtPagos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbIdPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbIdPedido)
                        .addGap(18, 18, 18)
                        .addComponent(rbFecha))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarPago)
                            .addComponent(txtBuscarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiarBPagos)
                            .addComponent(jdcBuscarxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIdPago)
                    .addComponent(rbIdPedido)
                    .addComponent(rbFecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcBuscarxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPago)
                    .addComponent(btnLimpiarBPagos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Consultar Pagos del Pedido", jPanel3);

        jLabel6.setText("IdPago");

        jLabel7.setText("IdPedido");

        jLabel8.setText("IdCliente");

        jLabel9.setText("Valor");

        btnbxidpago.setText("Buscar");

        btnbxidpedido.setText("Buscar");
        btnbxidpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbxidpedidoActionPerformed(evt);
            }
        });

        btnbxidcliente.setText("Buscar");

        jLabel10.setText("Lugar del Pago");

        jLabel25.setText("Fecha");

        jLabel26.setText("Comprobante");

        cbxlugarpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        txtcompobante.setBackground(new java.awt.Color(102, 102, 102));
        txtcompobante.setOpaque(true);

        btnExaminar.setText("Examinar");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar)
                    .addComponent(btnGuardar))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtidcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(txtidpedido)
                    .addComponent(txtidpago)
                    .addComponent(txtvalor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnbxidpago)
                        .addComponent(btnbxidpedido, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnbxidcliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExaminar)
                    .addComponent(jdcfechapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxlugarpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcompobante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtidpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbxidpago)
                                    .addComponent(jLabel10)
                                    .addComponent(cbxlugarpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtidpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbxidpedido)
                                    .addComponent(jLabel25)))
                            .addComponent(jdcfechapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbxidcliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExaminar)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(txtcompobante, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Registrar Pagos del Pedido", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelinfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelinfPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelinfEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelinfEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelinfPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelinfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poblarSedes() {
        try {
            PagosC obj = new PagosC();
            CachedRowSet crs = obj.poblarLugar();
            while (crs.next()) {
                cbxlugarpago.addItem(crs.getString(2));
            }

        } catch (Exception ex) {
            Logger.getLogger(JDPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CargarCargo() {
        ConfigC cc = new ConfigC();
        try {
            for (String cg : cc.poblarCargo()) {
                cbxCargo.addItem(cg);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    private void obtenerFecha() {
        Calendar cal = Calendar.getInstance();
        String fecha = "" + cal.get(Calendar.YEAR);
        fecha += "-" + (cal.get(Calendar.MONTH) + 1);
        fecha += "-" + cal.get(Calendar.DAY_OF_MONTH);
        jdcfechapago.setDate(Date.valueOf(fecha));
    }

    public void traerCodP() {
        PagosC pC = new PagosC();
        try {
            txtidpago.setText("" + pC.traerCodP());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        PagosC pc = new PagosC();
        pc.setIdPago(Integer.parseInt(txtidpago.getText()));
        pc.setIdPedido(Integer.parseInt(txtidpedido.getText()));
        pc.setDocCliente(Integer.parseInt(txtidcliente.getText()));
        pc.setValorPagado(Integer.parseInt(txtvalor.getText()));
        pc.setLugarPago(cbxlugarpago.getSelectedItem().toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        pc.setFecha(sdf.format(jdcfechapago.getDate()));
        pc.setComprobante(txtcompobante.getText());
        if (txtcompobante.getText().equals("")) {
            txtcompobante.setText("NULL");
        }

        try {
            String rta = pc.ModPago();
            JOptionPane.showMessageDialog(this, rta);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    private void limpiarCliente() {
        txtidCliente.setText("");
        txtNomCliente.setText("");
        txtTelCliente.setText("");
        txtDirCliente.setText("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void limpiarPedido() {
        txtCodPedido1.setText("");
        txtFechaPedido1.setText("");
        cbxFormaPago1.setSelectedIndex(0);
        cbEstadoPed.setSelected(false);
    }

    private void limpiarEmpleado() {
        txtidEmpleado.setText("");
        txtNomEmp.setText("");
        txtApeEmp.setText("");
        cbxGeneroEmp.setSelectedIndex(0);
        cbxCargo.setSelectedIndex(0);
    }

    private void limpiarPagos() {
        txtCantPagos.setText("");
        txtValorDeuda.setText("");
        txtValorPagado.setText("");
        txtValorTotal.setText("");
        dtm2.setNumRows(0);
    }
    
    private void limpiarDatosPagos(){
        txtidcliente.setText("");
        
        txtidpago.setText("");
        txtidpedido.setText("");
        txtvalor.setText("");
        jdcfechapago.setDate(null);
        cbxlugarpago.setSelectedIndex(0);
        txtcompobante.setText("");
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (cbxFormaPago1.getSelectedItem().toString().equals("Contado")) {
            //JOptionPane.showMessageDialog(this, "Pedido que se pagan de contado no pueden ser diferidos en cuotas\nDeben pagarse en su totalidad una sola vez");
            if (Integer.parseInt(txtvalor.getText()) > Double.parseDouble(txtValorDeuda.getText())) {
                JOptionPane.showMessageDialog(this, "No se puede registrar pagos mayores a la deuda");
            } else if (Integer.parseInt(txtvalor.getText()) < Double.parseDouble(txtValorDeuda.getText())) {
                JOptionPane.showMessageDialog(this, "pedidos de contado deben ser pagados en su totalidad");
            } else {
                PagosC pc = new PagosC();
                pc.setIdPago(Integer.parseInt(txtidpago.getText()));
                pc.setIdPedido(Integer.parseInt(txtidpedido.getText()));
                pc.setDocCliente(Integer.parseInt(txtidcliente.getText()));
                pc.setValorPagado(Integer.parseInt(txtvalor.getText()));
                pc.setLugarPago(cbxlugarpago.getSelectedItem().toString());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                pc.setFecha(sdf.format(jdcfechapago.getDate()));
                pc.setComprobante(txtcompobante.getText());
                if (txtcompobante.getText().equals("")) {
                    txtcompobante.setText("NULL");
                }
                try {
                    String rta = pc.regPago();
                    JOptionPane.showMessageDialog(this, rta);
                    limpiarCliente();
                    limpiarEmpleado();
                    limpiarPagos();
                    limpiarPedido();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.toString());
                }
            }
        } else {

            if (Integer.parseInt(txtvalor.getText()) > Double.parseDouble(txtValorDeuda.getText())) {
                JOptionPane.showMessageDialog(this, "No se puede registrar pagos mayores a la deuda");
            } else {
                PagosC pc = new PagosC();
                pc.setIdPago(Integer.parseInt(txtidpago.getText()));
                pc.setIdPedido(Integer.parseInt(txtidpedido.getText()));
                pc.setDocCliente(Integer.parseInt(txtidcliente.getText()));
                pc.setValorPagado(Integer.parseInt(txtvalor.getText()));
                pc.setLugarPago(cbxlugarpago.getSelectedItem().toString());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                pc.setFecha(sdf.format(jdcfechapago.getDate()));
                pc.setComprobante(txtcompobante.getText());
                if (txtcompobante.getText().equals("")) {
                    txtcompobante.setText("NULL");
                }
                try {
                    String rta = pc.regPago();
                    JOptionPane.showMessageDialog(this, rta);
                    limpiarCliente();
                    limpiarEmpleado();
                    limpiarPagos();
                    limpiarPedido();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.toString());
                }
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnbxidpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbxidpedidoActionPerformed
        try {

            dtm.setRowCount(0);
            PagosC obj = new PagosC();

            CachedRowSet crs = obj.buscarInfo(Integer.parseInt(txtidpedido.getText()));
            crs.next();
            txtCodPedido1.setText(String.valueOf(crs.getInt(1)));
            txtFechaPedido1.setText(crs.getString(5));
            cbxFormaPago1.setSelectedItem(crs.getString(6));
            cbEstadoPed.setSelected(crs.getBoolean(7));
            txtidCliente.setText(String.valueOf(crs.getInt(16)));
            txtNomCliente.setText(crs.getString(18));
            txtTelCliente.setText(String.valueOf(crs.getInt(20)));
            txtDirCliente.setText(crs.getString(22));
            txtidEmpleado.setText(String.valueOf(crs.getInt(8)));
            txtNomEmp.setText(crs.getString(11));
            txtApeEmp.setText(crs.getString(12));
            cbxGeneroEmp.setSelectedItem(crs.getString(13));

            obj = new PagosC();
            //CachedRowSet crs;
            crs = null;
            crs = obj.buscarInfDetalle(Integer.parseInt(txtidpedido.getText()));

            while (crs.next()) {
                v[0] = crs.getInt(3);
                v[1] = crs.getString("Nombre");
                v[2] = crs.getInt(5);
                v[3] = crs.getInt(4);
                v[4] = crs.getInt(5) * crs.getInt(4);

                dtm.addRow(v);
            }

        } catch (Exception ex) {
            Logger.getLogger(JDPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbxidpedidoActionPerformed

    private void btnBuscarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPagoActionPerformed
        PagosC pc = new PagosC();
        if (rbIdPedido.isSelected()) {
            try {
                pc.setIdPedido(Integer.parseInt(txtBuscarPagos.getText()));
                CachedRowSet crs = pc.BuscarPago();
                dtm.setNumRows(0);
                while (crs.next()) {
                    v[0] = crs.getInt(1);
                    v[1] = crs.getInt(2);
                    v[2] = crs.getDate(5);
                    v[3] = crs.getInt(3);
                    v[4] = crs.getString(7);
                    dtm.addRow(v);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        } else if (rbIdPago.isSelected()) {
            try {
                pc.setIdPago(Integer.parseInt(txtBuscarPagos.getText()));
                CachedRowSet crs = pc.BuscarPago2();
                dtm.setNumRows(0);
                while (crs.next()) {
                    v[0] = crs.getInt(1);
                    v[1] = crs.getInt(2);
                    v[2] = crs.getDate(5);
                    v[3] = crs.getInt(3);
                    v[4] = crs.getString(7);
                    dtm.addRow(v);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        } else if (rbFecha.isSelected()) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                pc.setFecha(sdf.format(jdcBuscarxFecha.getDate()));
                CachedRowSet crs = pc.BuscarPago3();
                dtm.setNumRows(0);
                while (crs.next()) {
                    v[0] = crs.getInt(1);
                    v[1] = crs.getInt(2);
                    v[2] = crs.getDate(5);
                    v[3] = crs.getInt(3);
                    v[4] = crs.getString(7);
                    dtm.addRow(v);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        }
    }//GEN-LAST:event_btnBuscarPagoActionPerformed

    private void txtCodPedido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodPedido1KeyTyped
        dtm2.setNumRows(0);
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            PagosC pc = new PagosC();
            pc.setIdPedido(Integer.parseInt(txtCodPedido1.getText()));

            try {
                CachedRowSet crs = pc.BuscarPag();
                while (crs.next()) {
                    if (crs.isFirst()) {
                        txtCodPedido1.setText(crs.getString(1));
                        txtidpedido.setText(crs.getString(1));
                        txtidEmpleado.setText(crs.getString(2));
                        txtidcliente.setText(crs.getString(3));
                        txtidCliente.setText(crs.getString(3));
                        txtNomCliente.setText(crs.getString(4));
                        txtTelCliente.setText(crs.getString(5));
                        txtDirCliente.setText(crs.getString(6));
                        txtFechaPedido1.setText(crs.getString(7));
                        jdcFentrega1.setDate(crs.getDate(8));
                        cbxFormaPago1.setSelectedItem(crs.getString(9));
                        cbEstadoPed.setSelected(crs.getBoolean(10));
                        txtNomEmp.setText(crs.getString(17));
                        txtApeEmp.setText(crs.getString(18));
                        cbxGeneroEmp.setSelectedItem(crs.getString(19));
                        cbxCargo.setSelectedItem(crs.getString(20));
                    }
                    v2[0] = crs.getString(11);
                    v2[1] = crs.getString(12);
                    v2[2] = crs.getString(14);
                    v2[3] = crs.getString(13);
                    v2[4] = (int) (((crs.getInt(14) * crs.getInt(13)) - crs.getFloat(15)) * 1.16);
                    dtm2.addRow(v2);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
            try {
                CachedRowSet crs2 = pc.BuscarDetallePago();
                crs2.next();
                txtValorPagado.setText(crs2.getString(2));
                txtValorTotal.setText(String.valueOf(Math.round(Float.parseFloat(crs2.getString(1)))));
                txtValorDeuda.setText(String.valueOf(Math.round(Float.parseFloat(crs2.getString(3)))));
                txtCantPagos.setText(crs2.getString(4));

                if (txtValorTotal.getText().equals("")) {
                    int cont = jtablaProd.getRowCount();
                    double tot = 0;
                    for (int i = 0; i < cont; i++) {
                        tot = tot + (Double.parseDouble(dtm2.getValueAt(i, 4).toString()));
                    }
                    txtValorTotal.setText("" + tot);
                    txtValorDeuda.setText(txtValorTotal.getText());
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        }

    }//GEN-LAST:event_txtCodPedido1KeyTyped

    private void btnLimpiarBPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBPagosActionPerformed
        txtBuscarPagos.setText("");
        jdcBuscarxFecha.setDate(null);
        rbFecha.setSelected(false);
        rbIdPago.setSelected(false);
        rbIdPedido.setSelected(false);
        dtm.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarBPagosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCliente();
        limpiarEmpleado();
        limpiarPagos();
        limpiarPedido();
        limpiarDatosPagos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPagos dialog = new JDPagos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarPago;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarBPagos;
    private javax.swing.JButton btnbxidcliente;
    private javax.swing.JButton btnbxidpago;
    private javax.swing.JButton btnbxidpedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbEstadoPed;
    private javax.swing.JComboBox<String> cbxCargo;
    private javax.swing.JComboBox<String> cbxFormaPago1;
    private javax.swing.JComboBox<String> cbxGeneroEmp;
    private javax.swing.JComboBox<String> cbxlugarpago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelinfCliente;
    private javax.swing.JPanel jPanelinfEmpleado;
    private javax.swing.JPanel jPanelinfPedido1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private com.toedter.calendar.JDateChooser jdcBuscarxFecha;
    private com.toedter.calendar.JDateChooser jdcFentrega1;
    private com.toedter.calendar.JDateChooser jdcfechapago;
    private javax.swing.JTable jtPagos;
    private javax.swing.JTable jtablaProd;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JRadioButton rbIdPago;
    private javax.swing.JRadioButton rbIdPedido;
    private javax.swing.JTextField txtApeEmp;
    private javax.swing.JTextField txtBuscarPagos;
    private javax.swing.JTextField txtCantPagos;
    private javax.swing.JTextField txtCodPedido1;
    private javax.swing.JTextField txtDirCliente;
    private javax.swing.JTextField txtFechaPedido1;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtNomEmp;
    private javax.swing.JTextField txtTelCliente;
    private javax.swing.JTextField txtValorDeuda;
    private javax.swing.JTextField txtValorPagado;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JLabel txtcompobante;
    private javax.swing.JTextField txtidCliente;
    private javax.swing.JTextField txtidEmpleado;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtidpago;
    private javax.swing.JTextField txtidpedido;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
