/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author Andres
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPedidos
     */
    public JFPrincipal() {
        initComponents();
         this.setSize(530, 490);
         this.setLocationRelativeTo(null);
        this.jmModifCliente.setOpaque(true);
        this.jmEmpleado.setOpaque(true);
        this.jMenu3.setOpaque(true);
        this.jmRegistrarP.setOpaque(true);
        this.jMenu7.setOpaque(true);
        this.jMenu8.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmEmpleado = new javax.swing.JMenu();
        jmRegistrarE = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmModifCliente = new javax.swing.JMenu();
        jmRegCliente = new javax.swing.JMenuItem();
        jmModif = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmRegistrarP = new javax.swing.JMenu();
        JMRegistrarP = new javax.swing.JMenuItem();
        jmConsultarP = new javax.swing.JMenuItem();
        jmEliminarP = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jmGestionarPed = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmCategoria = new javax.swing.JMenuItem();
        jmTipoDoc = new javax.swing.JMenuItem();
        jmCargos = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-pantalla-2.jpg"))); // NOI18N

        jmEmpleado.setBackground(new java.awt.Color(0, 51, 255));
        jmEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        jmEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_154-man-office-worker-2_3099407-2.png"))); // NOI18N
        jmEmpleado.setText("Empleado");
        jmEmpleado.setBorderPainted(true);
        jmEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmEmpleado.setOpaque(false);
        jmEmpleado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jmRegistrarE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        jmRegistrarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_document-save_118916.png"))); // NOI18N
        jmRegistrarE.setText("Registrar");
        jmRegistrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarEActionPerformed(evt);
            }
        });
        jmEmpleado.add(jmRegistrarE);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.META_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_compose_1055085.png"))); // NOI18N
        jMenuItem2.setText("Modificar-consultar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmEmpleado.add(jMenuItem2);
        jmEmpleado.add(jSeparator1);

        jMenuBar1.add(jmEmpleado);

        jmModifCliente.setBackground(new java.awt.Color(0, 255, 0));
        jmModifCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_users_61816.png"))); // NOI18N
        jmModifCliente.setText("Cliente");
        jmModifCliente.setBorderPainted(true);
        jmModifCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmModifCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jmRegCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_document-save_118916.png"))); // NOI18N
        jmRegCliente.setText("Registrar");
        jmRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegClienteActionPerformed(evt);
            }
        });
        jmModifCliente.add(jmRegCliente);

        jmModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_compose_1055085.png"))); // NOI18N
        jmModif.setText("Modificar-Consultar");
        jmModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModifActionPerformed(evt);
            }
        });
        jmModifCliente.add(jmModif);
        jmModifCliente.add(jSeparator2);

        jMenuBar1.add(jmModifCliente);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_Purse_669953.png"))); // NOI18N
        jMenu3.setText("Pagos");
        jMenu3.setBorderPainted(true);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setText("Gestionar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jmRegistrarP.setBackground(new java.awt.Color(0, 51, 255));
        jmRegistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_packing_49602.png"))); // NOI18N
        jmRegistrarP.setText("Productos");
        jmRegistrarP.setBorderPainted(true);
        jmRegistrarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmRegistrarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        JMRegistrarP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.META_MASK));
        JMRegistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_compose_1055085.png"))); // NOI18N
        JMRegistrarP.setText("Registrar");
        JMRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMRegistrarPActionPerformed(evt);
            }
        });
        jmRegistrarP.add(JMRegistrarP);

        jmConsultarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_Citycons_magnify_1342938.png"))); // NOI18N
        jmConsultarP.setText("Consultar");
        jmConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarPActionPerformed(evt);
            }
        });
        jmRegistrarP.add(jmConsultarP);

        jmEliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_trash_173120.png"))); // NOI18N
        jmEliminarP.setText("Eliminar");
        jmEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarPActionPerformed(evt);
            }
        });
        jmRegistrarP.add(jmEliminarP);
        jmRegistrarP.add(jSeparator3);

        jMenuBar1.add(jmRegistrarP);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_order-history_49596.png"))); // NOI18N
        jMenu7.setText("Pedidos");
        jMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jmGestionarPed.setText("Gestionar Pedido");
        jmGestionarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGestionarPedActionPerformed(evt);
            }
        });
        jMenu7.add(jmGestionarPed);

        jMenuBar1.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(0, 51, 255));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_Settings-5_379393.png"))); // NOI18N
        jMenu8.setText("Configuracion");
        jMenu8.setBorderPainted(true);
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jmCategoria.setText("Categoria");
        jmCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCategoriaActionPerformed(evt);
            }
        });
        jMenu8.add(jmCategoria);

        jmTipoDoc.setText("Tipo Documento");
        jmTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTipoDocActionPerformed(evt);
            }
        });
        jMenu8.add(jmTipoDoc);

        jmCargos.setText("Cargos");
        jmCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargosActionPerformed(evt);
            }
        });
        jMenu8.add(jmCargos);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmRegistrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarEActionPerformed
        
        JDEmpleados obj = new JDEmpleados(this,true);
        JDEmpleados.btnModificar.setEnabled(false);
        JDEmpleados.btnBuscarCli.setEnabled(false);
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
    }//GEN-LAST:event_jmRegistrarEActionPerformed

    private void JMRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMRegistrarPActionPerformed
        JDGestion objG = new JDGestion(this,true);
        objG.setLocationRelativeTo(null);
        JDGestion.txtDescripcion.setEnabled(false);
        JDGestion.lblDescripcion.setEnabled(false);
        JDGestion.btnActualizar.setEnabled(false);
        JDGestion.btnEliminar.setEnabled(false);
        JDGestion.btnMostrar.setEnabled(false);
        JDGestion.txtBuscar.setEnabled(false);
        JDGestion.jTableP.setEnabled(false);
        objG.setVisible(true);
    }//GEN-LAST:event_JMRegistrarPActionPerformed

    private void jmConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarPActionPerformed
        JDGestion objG = new JDGestion(this,true);
        objG.setLocationRelativeTo(null);
        JDGestion.txtDescripcion.setEnabled(false);
        JDGestion.lblDescripcion.setEnabled(false);
        JDGestion.btnActualizar.setEnabled(false);
        JDGestion.btnEliminar.setEnabled(false);
        JDGestion.btnGuardar.setEnabled(false);
        JDGestion.btnActualizar.setEnabled(true);
        habPanelProd(false);
        JDGestion.btnMostrar.setEnabled(true);
        objG.setVisible(true);
    }//GEN-LAST:event_jmConsultarPActionPerformed

    private void jmEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarPActionPerformed
        JDGestion objG = new JDGestion(this,true);
        objG.setLocationRelativeTo(null);
        JDGestion.txtDescripcion.setEnabled(false);
        JDGestion.lblDescripcion.setEnabled(false);
        JDGestion.btnActualizar.setEnabled(false);
        JDGestion.btnEliminar.setEnabled(true);
        JDGestion.btnGuardar.setEnabled(false);
        habPanelProd(false);
        JDGestion.btnMostrar.setEnabled(true);
        objG.setVisible(true);
    }//GEN-LAST:event_jmEliminarPActionPerformed

    private void jmCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCategoriaActionPerformed
        JDConfiguracion obj = new JDConfiguracion(this,true,"Categoria");
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
    }//GEN-LAST:event_jmCategoriaActionPerformed

    private void jmTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTipoDocActionPerformed
        JDConfiguracion obj = new JDConfiguracion(this,true,"Tipo Documento");
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
    }//GEN-LAST:event_jmTipoDocActionPerformed

    private void jmCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargosActionPerformed
        JDConfiguracion obj = new JDConfiguracion(this,true,"Cargos");
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
    }//GEN-LAST:event_jmCargosActionPerformed

    private void jmGestionarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGestionarPedActionPerformed
        JDPedidos obj = new JDPedidos(this, true);
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
    }//GEN-LAST:event_jmGestionarPedActionPerformed

    private void jmRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegClienteActionPerformed
        JDClientes obj = new JDClientes(this, true);
        JDClientes.btnModificar.setEnabled(false);
        
        JDClientes.btnBuscarCli.setEnabled(false);
        obj.setVisible(true);
    }//GEN-LAST:event_jmRegClienteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDEmpleados obj = new JDEmpleados(this,true);
        
        JDEmpleados.btnModificar.setEnabled(true);
        JDEmpleados.btnBuscarCli.setEnabled(true);
        
        JDEmpleados.btnRegistrar.setEnabled(false);
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModifActionPerformed
        JDClientes obj = new JDClientes(this, true);
        JDClientes.btnModificar.setEnabled(true);
        JDClientes.btnBuscarCli.setEnabled(true);
        
        JDClientes.btnRegistrar.setEnabled(false);
        obj.setVisible(true);
        
    }//GEN-LAST:event_jmModifActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDPagos obj = new JDPagos(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void habPanelProd(boolean estado){
        for (Component objPanel : JDGestion.jPanelProducto.getComponents()) {
            objPanel.setEnabled(estado);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMRegistrarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem jmCargos;
    private javax.swing.JMenuItem jmCategoria;
    private javax.swing.JMenuItem jmConsultarP;
    private javax.swing.JMenuItem jmEliminarP;
    private javax.swing.JMenu jmEmpleado;
    private javax.swing.JMenuItem jmGestionarPed;
    private javax.swing.JMenuItem jmModif;
    private javax.swing.JMenu jmModifCliente;
    private javax.swing.JMenuItem jmRegCliente;
    private javax.swing.JMenuItem jmRegistrarE;
    private javax.swing.JMenu jmRegistrarP;
    private javax.swing.JMenuItem jmTipoDoc;
    // End of variables declaration//GEN-END:variables
}
